// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyBdDBaL64QK6c4QnIjFQlmY8SdDOslUA',
    appId: '1:1064484953640:web:27011a67ed0641c51e5f1d',
    messagingSenderId: '1064484953640',
    projectId: 'fluentmind-6d476',
    authDomain: 'fluentmind-6d476.firebaseapp.com',
    storageBucket: 'fluentmind-6d476.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB3wB0HzY6bMqQQtGDSl90oUEfMATdfTs',
    appId: '1:1064484953640:android:e0b129ef845bdeea1e5f1d',
    messagingSenderId: '1064484953640',
    projectId: 'fluentmind-6d476',
    storageBucket: 'fluentmind-6d476.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtoxKqLSRBPQowSVGS3xPRM17ir4Tmrws',
    appId: '1:1064484953640:ios:3d0fdcd14fcb91e91e5f1d',
    messagingSenderId: '1064484953640',
    projectId: 'fluentmind-6d476',
    storageBucket: 'fluentmind-6d476.firebasestorage.app',
    iosBundleId: 'com.fluentmind.fluentmind',
  );
}
